-- 0009_seed_authorization.sql
-- Seed data minimal supaya migration bisa langsung dites (item 6 dari rincian Step 1).
--
-- roles: 7 baris, sumber STEP12-01_ROLE_CATALOGUE_FULL.csv (LOCKED, Platform role).
-- Baris Guest & ORG-ADMIN SENGAJA TIDAK dibuat sebagai role row karena sumber
-- eksplisit menyebut keduanya "NOT A PLATFORM ROLE".
--
-- permissions: 90 baris, diturunkan deterministik dari 50 baris
-- STEP12-01_ROLE_PERMISSION_MASTER_MATRIX.csv (format module.resource.action).
--
-- role_permissions: 345 grant (ALL/OWN), sumber sama, generate otomatis dari CSV
-- (bukan diketik manual) supaya 1:1 traceable ke dokumen — lihat
-- audit/ROLE_PERMISSION_SEED_TRACEABILITY.csv untuk mapping asal tiap baris.

INSERT INTO public.roles (code, name, is_system_role, is_protected) VALUES
  ('superadmin',        'Superadmin',        true, true),
  ('admin',             'Admin',             true, true),
  ('manager',           'Manager',           true, true),
  ('agent',             'Agent',             true, true),
  ('developer_partner', 'Developer Partner', true, true),
  ('buyer',             'Buyer',             true, true),
  ('instructor',        'Instructor',        true, true)
ON CONFLICT (code) DO NOTHING;

-- dbr_config: satu baris default supaya tabel tidak kosong saat pertama dites.
INSERT INTO public.dbr_config (dbr_threshold_percent, default_interest_rate)
SELECT 35.00, 8.50
WHERE NOT EXISTS (SELECT 1 FROM public.dbr_config);


-- Auto-generated from STEP12-01_ROLE_PERMISSION_MASTER_MATRIX.csv (50 baris frozen, 90 permission unik)
INSERT INTO permissions (module_code, action_code, scope_type, description) VALUES
  ('m02', 'm02.profile_photo.upload', 'own', 'Profile Photo - Upload (Own profile for non-Superadmin roles)'),
  ('m02', 'm02.profile_photo.edit', 'own', 'Profile Photo - Edit (Own profile for non-Superadmin roles)'),
  ('m02', 'm02.profile_photo.delete', 'own', 'Profile Photo - Delete (Own profile for non-Superadmin roles)'),
  ('m03', 'm03.listing.create', 'own', 'Listing - Create (Lifecycle/ownership guards)'),
  ('m03', 'm03.listing.update', 'own', 'Listing - Update (Ordinary owner edit; moderation separate)'),
  ('m03', 'm03.listing.delete', 'own', 'Listing - Delete (Lifecycle/ownership guards)'),
  ('m03', 'm03.listing.publish', 'own', 'Listing - Publish (Publication rules)'),
  ('m03', 'm03.listing.refresh', 'own', 'Listing - Refresh (PUBLISHED + owner/authority + daily entitlement + operational day + once/listing/day)'),
  ('m04', 'm04.learning_session.create', 'own', 'Learning Session - Create (Instructor resource/assignment constrained; Host is capability, not Role)'),
  ('m04', 'm04.learning_session.view', 'own', 'Learning Session - View (Visibility + resource/eligibility)'),
  ('m04', 'm04.learning_session.update', 'own', 'Learning Session - Update (Resource/assignment/lifecycle)'),
  ('m04', 'm04.learning_session.delete', 'own', 'Learning Session - Delete (Lifecycle constraints)'),
  ('m04', 'm04.learning_session.manage', 'own', 'Learning Session - Manage (Instructor constrained to assigned resource)'),
  ('m04', 'm04.session_enrollment.create', 'own', 'Session Enrollment - Create (Own enrollment/access eligibility)'),
  ('m04', 'm04.session_enrollment.view', 'own', 'Session Enrollment - View (Own enrollment/access eligibility)'),
  ('m04', 'm04.session_assignment.assign', 'own', 'Session Assignment - Assign (Privileged assignment mutation)'),
  ('m04', 'm04.session_evidence.view', 'own', 'Session Evidence - View (Own/resource/assignment constraints)'),
  ('m04', 'm04.session_evidence.manage', 'own', 'Session Evidence - Manage (Own/resource/assignment constraints)'),
  ('m04', 'm04.attendance.manage', 'own', 'Attendance - Manage (Assigned resource)'),
  ('m04', 'm04.completion.manage', 'own', 'Completion - Manage (Learner cannot authoritatively mutate completion outcome)'),
  ('m04', 'm04.artifact.view', 'own', 'Artifact - View (Resource/participant context)'),
  ('m04', 'm04.artifact.manage', 'own', 'Artifact - Manage (Resource/participant context)'),
  ('m04', 'm04.learning_provider.manage', 'own', 'Learning Provider - Manage (Privileged provider management)'),
  ('m05', 'm05.event.create', 'own', 'Event - Create (Submission does not imply publish)'),
  ('m05', 'm05.event.update', 'own', 'Event - Update (Submission does not imply publish)'),
  ('m05', 'm05.event.publish', 'own', 'Event - Publish (Submission does not imply publish)'),
  ('m05', 'm05.event.lifecycle', 'own', 'Event - Lifecycle (Submission does not imply publish)'),
  ('m05', 'm05.event.visibility', 'own', 'Event - Visibility (Submission does not imply publish)'),
  ('m05', 'm05.event_registration.create', 'own', 'Event Registration - Create (Own registration + eligibility)'),
  ('m05', 'm05.event_registration.view', 'own', 'Event Registration - View (Own registration + eligibility)'),
  ('m05', 'm05.event_registration.update', 'own', 'Event Registration - Update (Own registration + eligibility)'),
  ('m05', 'm05.event.cancellation', 'own', 'Event - Cancellation (Separate M05 lifecycle authority)'),
  ('m05', 'm05.guest_registration.create', 'own', 'Guest Registration - Create (Distinct from M04 Session Enrollment)'),
  ('m05', 'm05.guest_registration.view', 'own', 'Guest Registration - View (Distinct from M04 Session Enrollment)'),
  ('m05', 'm05.guest_registration.manage', 'own', 'Guest Registration - Manage (Distinct from M04 Session Enrollment)'),
  ('m06', 'm06.marketing_kit.create', 'own', 'Marketing Kit - Create (Developer Partner own developer/project scope)'),
  ('m06', 'm06.marketing_kit.upload', 'own', 'Marketing Kit - Upload (Developer Partner own developer/project scope)'),
  ('m06', 'm06.marketing_kit.edit', 'own', 'Marketing Kit - Edit (Developer Partner own developer/project scope)'),
  ('m06', 'm06.marketing_kit.delete', 'own', 'Marketing Kit - Delete (Developer Partner own developer/project scope)'),
  ('m06', 'm06.marketing_kit.view', 'own', 'Marketing Kit - View (Manager/Agent view+download; Developer Partner own)'),
  ('m06', 'm06.marketing_kit.download', 'own', 'Marketing Kit - Download (Manager/Agent view+download; Developer Partner own)'),
  ('m06', 'm06.claim.review', 'own', 'Claim - Review (Claim/project moderation rules)'),
  ('m06', 'm06.claim.approve', 'own', 'Claim - Approve (Claim/project moderation rules)'),
  ('m06', 'm06.claim.reject', 'own', 'Claim - Reject (Claim/project moderation rules)'),
  ('m06', 'm06.claim.revoke', 'own', 'Claim - Revoke (Claim/project moderation rules)'),
  ('m07', 'm07.dbr.domain_operations', 'own', 'DBR - Domain operations (Bank Selection is not a standalone permission)'),
  ('m08', 'm08.dashboard_projection.project', 'own', 'Dashboard Projection - Project (Projection only)'),
  ('m08', 'm08.dashboard_projection.read', 'own', 'Dashboard Projection - Read (Projection only)'),
  ('m08', 'm08.notification_state.read', 'own', 'Notification State - Read (State/communication only)'),
  ('m08', 'm08.notification_state.update_state', 'own', 'Notification State - Update State (State/communication only)'),
  ('m09', 'm09.system_configuration.view', 'own', 'System Configuration - View (System configuration boundary)'),
  ('m09', 'm09.system_configuration.manage', 'own', 'System Configuration - Manage (System configuration boundary)'),
  ('m09', 'm09.administrative_audit_log.view', 'own', 'Administrative Audit Log - View (Administrative audit boundary)'),
  ('m09', 'm09.notification_template_content.configure', 'own', 'Notification Template/Content - Configure (Presentation/content config; source event remains domain-owned)'),
  ('m09', 'm09.administrative_export.export', 'own', 'Administrative Export - Export (Global administrative export)'),
  ('m09', 'm09.provider_catalogue.mutation', 'own', 'Provider Catalogue - Mutation (M13 domain authority; Superadmin-only mutation)'),
  ('m10', 'm10.role_catalogue.view', 'own', 'Role Catalogue - View (Authorization infrastructure)'),
  ('m10', 'm10.permission_catalogue.view', 'own', 'Permission Catalogue - View (Authorization infrastructure)'),
  ('m10', 'm10.role_permission_matrix.view', 'own', 'Role-Permission Matrix - View (Authorization infrastructure)'),
  ('m10', 'm10.role_permission_matrix.manage', 'own', 'Role-Permission Matrix - Manage (Protected governance)'),
  ('m10', 'm10.agent_permission_rows.modify', 'own', 'Agent Permission Rows - Modify (Manager may modify Agent rows only where editability allows)'),
  ('m11', 'm11.static_public_content.publish', 'own', 'Static Public Content - Publish (Publisher capability separate from discovery)'),
  ('m11', 'm11.announcement_promotion.publish', 'own', 'Announcement / Promotion - Publish (Discovery/measurement separate from authoring)'),
  ('m12', 'm12.organization.manage_within_authorized_context', 'own', 'Organization - Manage within authorized context (Organization context does not create Role/scope enum)'),
  ('m13', 'm13.provider_catalogue.create', 'own', 'Provider Catalogue - Create (Superadmin-only mutation)'),
  ('m13', 'm13.provider_catalogue.edit', 'own', 'Provider Catalogue - Edit (Superadmin-only mutation)'),
  ('m13', 'm13.provider_catalogue.enable', 'own', 'Provider Catalogue - Enable (Superadmin-only mutation)'),
  ('m13', 'm13.provider_catalogue.disable', 'own', 'Provider Catalogue - Disable (Superadmin-only mutation)'),
  ('m13', 'm13.provider_catalogue.retire', 'own', 'Provider Catalogue - Retire (Superadmin-only mutation)'),
  ('m13', 'm13.own_byok_connection.create', 'own', 'Own BYOK Connection - Create (Own connection; credentials remain infrastructure-controlled)'),
  ('m13', 'm13.own_byok_connection.view', 'own', 'Own BYOK Connection - View (Own connection; credentials remain infrastructure-controlled)'),
  ('m13', 'm13.own_byok_connection.update', 'own', 'Own BYOK Connection - Update (Own connection; credentials remain infrastructure-controlled)'),
  ('m13', 'm13.own_byok_connection.rotate', 'own', 'Own BYOK Connection - Rotate (Own connection; credentials remain infrastructure-controlled)'),
  ('m13', 'm13.own_byok_connection.test', 'own', 'Own BYOK Connection - Test (Own connection; credentials remain infrastructure-controlled)'),
  ('m13', 'm13.own_byok_connection.enable', 'own', 'Own BYOK Connection - Enable (Own connection; credentials remain infrastructure-controlled)'),
  ('m13', 'm13.own_byok_connection.disable', 'own', 'Own BYOK Connection - Disable (Own connection; credentials remain infrastructure-controlled)'),
  ('m13', 'm13.own_byok_connection.disconnect', 'own', 'Own BYOK Connection - Disconnect (Own connection; credentials remain infrastructure-controlled)'),
  ('m13', 'm13.administrative_force_revoke_disable.execute', 'own', 'Administrative Force Revoke/Disable - Execute (Privileged administrative intervention)'),
  ('m14', 'm14.commercial_administration.configure', 'own', 'Commercial Administration - Configure (Exact operation-level authority remains M14; entitlement is not RBAC)'),
  ('m14', 'm14.commercial_administration.manage_commercial_resources', 'own', 'Commercial Administration - manage commercial resources (Exact operation-level authority remains M14; entitlement is not RBAC)'),
  ('m14', 'm14.commercial_purchase_access.own_purchase', 'own', 'Commercial Purchase/Access - Own purchase (Purchase success does not grant RBAC; entitlement may affect eligibility)'),
  ('m14', 'm14.commercial_purchase_access.access', 'own', 'Commercial Purchase/Access - access (Purchase success does not grant RBAC; entitlement may affect eligibility)'),
  ('m14', 'm14.refresh_allowance_entitlement.configure', 'own', 'Refresh Allowance/Entitlement - Configure (M14 allowance/quota; M03 owns Refresh action)'),
  ('m14', 'm14.refresh_allowance_entitlement.consume', 'own', 'Refresh Allowance/Entitlement - consume (M14 allowance/quota; M03 owns Refresh action)'),
  ('m15', 'm15.qualification.administer', 'own', 'Qualification - Administer (Qualification is not authorization)'),
  ('m15', 'm15.qualification.evaluate', 'own', 'Qualification - evaluate (Qualification is not authorization)'),
  ('m15', 'm15.award.award', 'own', 'Award - Award (Requires applicable Authority/Scope Binding; no Issuer Role)'),
  ('m15', 'm15.award.revoke', 'own', 'Award - revoke (Requires applicable Authority/Scope Binding; no Issuer Role)'),
  ('m15', 'm15.award.manage', 'own', 'Award - manage (Requires applicable Authority/Scope Binding; no Issuer Role)'),
  ('m15', 'm15.title_authority_scope_binding.configure', 'own', 'Title Authority / Scope Binding - Configure (Separate from operational permission; no Issuer Role)')
ON CONFLICT (module_code, action_code) DO NOTHING;

-- Auto-generated role_permissions seed dari 345 grant (ALL/OWN) di master matrix
INSERT INTO role_permissions (role_id, permission_id, granted_scope, editable_by_role_code)
SELECT r.id, p.id, g.scope, 'superadmin'
FROM (VALUES
  ('superadmin', 'm02.profile_photo.upload', 'all'),
  ('admin', 'm02.profile_photo.upload', 'own'),
  ('manager', 'm02.profile_photo.upload', 'own'),
  ('agent', 'm02.profile_photo.upload', 'own'),
  ('developer_partner', 'm02.profile_photo.upload', 'own'),
  ('buyer', 'm02.profile_photo.upload', 'own'),
  ('instructor', 'm02.profile_photo.upload', 'own'),
  ('superadmin', 'm02.profile_photo.edit', 'all'),
  ('admin', 'm02.profile_photo.edit', 'own'),
  ('manager', 'm02.profile_photo.edit', 'own'),
  ('agent', 'm02.profile_photo.edit', 'own'),
  ('developer_partner', 'm02.profile_photo.edit', 'own'),
  ('buyer', 'm02.profile_photo.edit', 'own'),
  ('instructor', 'm02.profile_photo.edit', 'own'),
  ('superadmin', 'm02.profile_photo.delete', 'all'),
  ('admin', 'm02.profile_photo.delete', 'own'),
  ('manager', 'm02.profile_photo.delete', 'own'),
  ('agent', 'm02.profile_photo.delete', 'own'),
  ('developer_partner', 'm02.profile_photo.delete', 'own'),
  ('buyer', 'm02.profile_photo.delete', 'own'),
  ('instructor', 'm02.profile_photo.delete', 'own'),
  ('superadmin', 'm03.listing.create', 'all'),
  ('admin', 'm03.listing.create', 'all'),
  ('manager', 'm03.listing.create', 'all'),
  ('agent', 'm03.listing.create', 'own'),
  ('superadmin', 'm03.listing.update', 'all'),
  ('agent', 'm03.listing.update', 'own'),
  ('superadmin', 'm03.listing.delete', 'all'),
  ('admin', 'm03.listing.delete', 'all'),
  ('manager', 'm03.listing.delete', 'all'),
  ('agent', 'm03.listing.delete', 'own'),
  ('superadmin', 'm03.listing.publish', 'all'),
  ('admin', 'm03.listing.publish', 'all'),
  ('agent', 'm03.listing.publish', 'own'),
  ('superadmin', 'm03.listing.refresh', 'all'),
  ('agent', 'm03.listing.refresh', 'own'),
  ('superadmin', 'm04.learning_session.create', 'all'),
  ('admin', 'm04.learning_session.create', 'all'),
  ('manager', 'm04.learning_session.create', 'all'),
  ('instructor', 'm04.learning_session.create', 'own'),
  ('superadmin', 'm04.learning_session.view', 'all'),
  ('admin', 'm04.learning_session.view', 'all'),
  ('manager', 'm04.learning_session.view', 'all'),
  ('agent', 'm04.learning_session.view', 'own'),
  ('buyer', 'm04.learning_session.view', 'own'),
  ('instructor', 'm04.learning_session.view', 'own'),
  ('superadmin', 'm04.learning_session.update', 'all'),
  ('admin', 'm04.learning_session.update', 'all'),
  ('manager', 'm04.learning_session.update', 'all'),
  ('instructor', 'm04.learning_session.update', 'own'),
  ('superadmin', 'm04.learning_session.delete', 'all'),
  ('admin', 'm04.learning_session.delete', 'all'),
  ('manager', 'm04.learning_session.delete', 'all'),
  ('instructor', 'm04.learning_session.delete', 'own'),
  ('superadmin', 'm04.learning_session.manage', 'all'),
  ('admin', 'm04.learning_session.manage', 'all'),
  ('manager', 'm04.learning_session.manage', 'all'),
  ('instructor', 'm04.learning_session.manage', 'own'),
  ('superadmin', 'm04.session_enrollment.create', 'all'),
  ('admin', 'm04.session_enrollment.create', 'all'),
  ('manager', 'm04.session_enrollment.create', 'all'),
  ('agent', 'm04.session_enrollment.create', 'own'),
  ('buyer', 'm04.session_enrollment.create', 'own'),
  ('instructor', 'm04.session_enrollment.create', 'own'),
  ('superadmin', 'm04.session_enrollment.view', 'all'),
  ('admin', 'm04.session_enrollment.view', 'all'),
  ('manager', 'm04.session_enrollment.view', 'all'),
  ('agent', 'm04.session_enrollment.view', 'own'),
  ('buyer', 'm04.session_enrollment.view', 'own'),
  ('instructor', 'm04.session_enrollment.view', 'own'),
  ('superadmin', 'm04.session_assignment.assign', 'all'),
  ('admin', 'm04.session_assignment.assign', 'all'),
  ('manager', 'm04.session_assignment.assign', 'all'),
  ('superadmin', 'm04.session_evidence.view', 'all'),
  ('admin', 'm04.session_evidence.view', 'all'),
  ('manager', 'm04.session_evidence.view', 'all'),
  ('agent', 'm04.session_evidence.view', 'own'),
  ('buyer', 'm04.session_evidence.view', 'own'),
  ('instructor', 'm04.session_evidence.view', 'own'),
  ('superadmin', 'm04.session_evidence.manage', 'all'),
  ('admin', 'm04.session_evidence.manage', 'all'),
  ('manager', 'm04.session_evidence.manage', 'all'),
  ('agent', 'm04.session_evidence.manage', 'own'),
  ('buyer', 'm04.session_evidence.manage', 'own'),
  ('instructor', 'm04.session_evidence.manage', 'own'),
  ('superadmin', 'm04.attendance.manage', 'all'),
  ('admin', 'm04.attendance.manage', 'all'),
  ('manager', 'm04.attendance.manage', 'all'),
  ('instructor', 'm04.attendance.manage', 'own'),
  ('superadmin', 'm04.completion.manage', 'all'),
  ('admin', 'm04.completion.manage', 'all'),
  ('manager', 'm04.completion.manage', 'all'),
  ('instructor', 'm04.completion.manage', 'own'),
  ('superadmin', 'm04.artifact.view', 'all'),
  ('admin', 'm04.artifact.view', 'all'),
  ('manager', 'm04.artifact.view', 'all'),
  ('agent', 'm04.artifact.view', 'own'),
  ('buyer', 'm04.artifact.view', 'own'),
  ('instructor', 'm04.artifact.view', 'own'),
  ('superadmin', 'm04.artifact.manage', 'all'),
  ('admin', 'm04.artifact.manage', 'all'),
  ('manager', 'm04.artifact.manage', 'all'),
  ('agent', 'm04.artifact.manage', 'own'),
  ('buyer', 'm04.artifact.manage', 'own'),
  ('instructor', 'm04.artifact.manage', 'own'),
  ('superadmin', 'm04.learning_provider.manage', 'all'),
  ('admin', 'm04.learning_provider.manage', 'all'),
  ('manager', 'm04.learning_provider.manage', 'all'),
  ('superadmin', 'm05.event.create', 'all'),
  ('admin', 'm05.event.create', 'all'),
  ('manager', 'm05.event.create', 'all'),
  ('agent', 'm05.event.create', 'own'),
  ('instructor', 'm05.event.create', 'own'),
  ('superadmin', 'm05.event.update', 'all'),
  ('admin', 'm05.event.update', 'all'),
  ('manager', 'm05.event.update', 'all'),
  ('agent', 'm05.event.update', 'own'),
  ('instructor', 'm05.event.update', 'own'),
  ('superadmin', 'm05.event.publish', 'all'),
  ('admin', 'm05.event.publish', 'all'),
  ('manager', 'm05.event.publish', 'all'),
  ('agent', 'm05.event.publish', 'own'),
  ('instructor', 'm05.event.publish', 'own'),
  ('superadmin', 'm05.event.lifecycle', 'all'),
  ('admin', 'm05.event.lifecycle', 'all'),
  ('manager', 'm05.event.lifecycle', 'all'),
  ('agent', 'm05.event.lifecycle', 'own'),
  ('instructor', 'm05.event.lifecycle', 'own'),
  ('superadmin', 'm05.event.visibility', 'all'),
  ('admin', 'm05.event.visibility', 'all'),
  ('manager', 'm05.event.visibility', 'all'),
  ('agent', 'm05.event.visibility', 'own'),
  ('instructor', 'm05.event.visibility', 'own'),
  ('superadmin', 'm05.event_registration.create', 'all'),
  ('admin', 'm05.event_registration.create', 'all'),
  ('manager', 'm05.event_registration.create', 'all'),
  ('agent', 'm05.event_registration.create', 'own'),
  ('buyer', 'm05.event_registration.create', 'own'),
  ('instructor', 'm05.event_registration.create', 'own'),
  ('superadmin', 'm05.event_registration.view', 'all'),
  ('admin', 'm05.event_registration.view', 'all'),
  ('manager', 'm05.event_registration.view', 'all'),
  ('agent', 'm05.event_registration.view', 'own'),
  ('buyer', 'm05.event_registration.view', 'own'),
  ('instructor', 'm05.event_registration.view', 'own'),
  ('superadmin', 'm05.event_registration.update', 'all'),
  ('admin', 'm05.event_registration.update', 'all'),
  ('manager', 'm05.event_registration.update', 'all'),
  ('agent', 'm05.event_registration.update', 'own'),
  ('buyer', 'm05.event_registration.update', 'own'),
  ('instructor', 'm05.event_registration.update', 'own'),
  ('superadmin', 'm05.event.cancellation', 'all'),
  ('admin', 'm05.event.cancellation', 'all'),
  ('manager', 'm05.event.cancellation', 'all'),
  ('superadmin', 'm05.guest_registration.create', 'all'),
  ('admin', 'm05.guest_registration.create', 'all'),
  ('manager', 'm05.guest_registration.create', 'all'),
  ('instructor', 'm05.guest_registration.create', 'own'),
  ('superadmin', 'm05.guest_registration.view', 'all'),
  ('admin', 'm05.guest_registration.view', 'all'),
  ('manager', 'm05.guest_registration.view', 'all'),
  ('instructor', 'm05.guest_registration.view', 'own'),
  ('superadmin', 'm05.guest_registration.manage', 'all'),
  ('admin', 'm05.guest_registration.manage', 'all'),
  ('manager', 'm05.guest_registration.manage', 'all'),
  ('instructor', 'm05.guest_registration.manage', 'own'),
  ('superadmin', 'm06.marketing_kit.create', 'all'),
  ('admin', 'm06.marketing_kit.create', 'all'),
  ('manager', 'm06.marketing_kit.create', 'all'),
  ('developer_partner', 'm06.marketing_kit.create', 'own'),
  ('superadmin', 'm06.marketing_kit.upload', 'all'),
  ('admin', 'm06.marketing_kit.upload', 'all'),
  ('manager', 'm06.marketing_kit.upload', 'all'),
  ('developer_partner', 'm06.marketing_kit.upload', 'own'),
  ('superadmin', 'm06.marketing_kit.edit', 'all'),
  ('admin', 'm06.marketing_kit.edit', 'all'),
  ('manager', 'm06.marketing_kit.edit', 'all'),
  ('developer_partner', 'm06.marketing_kit.edit', 'own'),
  ('superadmin', 'm06.marketing_kit.delete', 'all'),
  ('admin', 'm06.marketing_kit.delete', 'all'),
  ('manager', 'm06.marketing_kit.delete', 'all'),
  ('developer_partner', 'm06.marketing_kit.delete', 'own'),
  ('superadmin', 'm06.marketing_kit.view', 'all'),
  ('admin', 'm06.marketing_kit.view', 'all'),
  ('manager', 'm06.marketing_kit.view', 'all'),
  ('agent', 'm06.marketing_kit.view', 'own'),
  ('developer_partner', 'm06.marketing_kit.view', 'own'),
  ('superadmin', 'm06.marketing_kit.download', 'all'),
  ('admin', 'm06.marketing_kit.download', 'all'),
  ('manager', 'm06.marketing_kit.download', 'all'),
  ('agent', 'm06.marketing_kit.download', 'own'),
  ('developer_partner', 'm06.marketing_kit.download', 'own'),
  ('superadmin', 'm06.claim.review', 'all'),
  ('admin', 'm06.claim.review', 'all'),
  ('manager', 'm06.claim.review', 'all'),
  ('agent', 'm06.claim.review', 'own'),
  ('developer_partner', 'm06.claim.review', 'own'),
  ('superadmin', 'm06.claim.approve', 'all'),
  ('admin', 'm06.claim.approve', 'all'),
  ('manager', 'm06.claim.approve', 'all'),
  ('agent', 'm06.claim.approve', 'own'),
  ('developer_partner', 'm06.claim.approve', 'own'),
  ('superadmin', 'm06.claim.reject', 'all'),
  ('admin', 'm06.claim.reject', 'all'),
  ('manager', 'm06.claim.reject', 'all'),
  ('agent', 'm06.claim.reject', 'own'),
  ('developer_partner', 'm06.claim.reject', 'own'),
  ('superadmin', 'm06.claim.revoke', 'all'),
  ('admin', 'm06.claim.revoke', 'all'),
  ('manager', 'm06.claim.revoke', 'all'),
  ('agent', 'm06.claim.revoke', 'own'),
  ('developer_partner', 'm06.claim.revoke', 'own'),
  ('superadmin', 'm07.dbr.domain_operations', 'all'),
  ('admin', 'm07.dbr.domain_operations', 'all'),
  ('manager', 'm07.dbr.domain_operations', 'all'),
  ('agent', 'm07.dbr.domain_operations', 'own'),
  ('superadmin', 'm08.dashboard_projection.project', 'all'),
  ('admin', 'm08.dashboard_projection.project', 'all'),
  ('manager', 'm08.dashboard_projection.project', 'all'),
  ('agent', 'm08.dashboard_projection.project', 'own'),
  ('developer_partner', 'm08.dashboard_projection.project', 'own'),
  ('buyer', 'm08.dashboard_projection.project', 'own'),
  ('instructor', 'm08.dashboard_projection.project', 'own'),
  ('superadmin', 'm08.dashboard_projection.read', 'all'),
  ('admin', 'm08.dashboard_projection.read', 'all'),
  ('manager', 'm08.dashboard_projection.read', 'all'),
  ('agent', 'm08.dashboard_projection.read', 'own'),
  ('developer_partner', 'm08.dashboard_projection.read', 'own'),
  ('buyer', 'm08.dashboard_projection.read', 'own'),
  ('instructor', 'm08.dashboard_projection.read', 'own'),
  ('superadmin', 'm08.notification_state.read', 'all'),
  ('admin', 'm08.notification_state.read', 'all'),
  ('manager', 'm08.notification_state.read', 'all'),
  ('agent', 'm08.notification_state.read', 'own'),
  ('developer_partner', 'm08.notification_state.read', 'own'),
  ('buyer', 'm08.notification_state.read', 'own'),
  ('instructor', 'm08.notification_state.read', 'own'),
  ('superadmin', 'm08.notification_state.update_state', 'all'),
  ('admin', 'm08.notification_state.update_state', 'all'),
  ('manager', 'm08.notification_state.update_state', 'all'),
  ('agent', 'm08.notification_state.update_state', 'own'),
  ('developer_partner', 'm08.notification_state.update_state', 'own'),
  ('buyer', 'm08.notification_state.update_state', 'own'),
  ('instructor', 'm08.notification_state.update_state', 'own'),
  ('superadmin', 'm09.system_configuration.view', 'all'),
  ('superadmin', 'm09.system_configuration.manage', 'all'),
  ('superadmin', 'm09.administrative_audit_log.view', 'all'),
  ('admin', 'm09.administrative_audit_log.view', 'all'),
  ('superadmin', 'm09.notification_template_content.configure', 'all'),
  ('admin', 'm09.notification_template_content.configure', 'all'),
  ('manager', 'm09.notification_template_content.configure', 'all'),
  ('superadmin', 'm09.administrative_export.export', 'all'),
  ('superadmin', 'm09.provider_catalogue.mutation', 'all'),
  ('superadmin', 'm10.role_catalogue.view', 'all'),
  ('admin', 'm10.role_catalogue.view', 'all'),
  ('manager', 'm10.role_catalogue.view', 'all'),
  ('superadmin', 'm10.permission_catalogue.view', 'all'),
  ('admin', 'm10.permission_catalogue.view', 'all'),
  ('manager', 'm10.permission_catalogue.view', 'all'),
  ('superadmin', 'm10.role_permission_matrix.view', 'all'),
  ('admin', 'm10.role_permission_matrix.view', 'all'),
  ('manager', 'm10.role_permission_matrix.view', 'all'),
  ('superadmin', 'm10.role_permission_matrix.manage', 'all'),
  ('superadmin', 'm10.agent_permission_rows.modify', 'all'),
  ('manager', 'm10.agent_permission_rows.modify', 'own'),
  ('superadmin', 'm11.static_public_content.publish', 'all'),
  ('admin', 'm11.static_public_content.publish', 'all'),
  ('superadmin', 'm11.announcement_promotion.publish', 'all'),
  ('admin', 'm11.announcement_promotion.publish', 'all'),
  ('superadmin', 'm12.organization.manage_within_authorized_context', 'all'),
  ('admin', 'm12.organization.manage_within_authorized_context', 'all'),
  ('manager', 'm12.organization.manage_within_authorized_context', 'own'),
  ('agent', 'm12.organization.manage_within_authorized_context', 'own'),
  ('developer_partner', 'm12.organization.manage_within_authorized_context', 'own'),
  ('buyer', 'm12.organization.manage_within_authorized_context', 'own'),
  ('instructor', 'm12.organization.manage_within_authorized_context', 'own'),
  ('superadmin', 'm13.provider_catalogue.create', 'all'),
  ('superadmin', 'm13.provider_catalogue.edit', 'all'),
  ('superadmin', 'm13.provider_catalogue.enable', 'all'),
  ('superadmin', 'm13.provider_catalogue.disable', 'all'),
  ('superadmin', 'm13.provider_catalogue.retire', 'all'),
  ('superadmin', 'm13.own_byok_connection.create', 'all'),
  ('developer_partner', 'm13.own_byok_connection.create', 'own'),
  ('superadmin', 'm13.own_byok_connection.view', 'all'),
  ('developer_partner', 'm13.own_byok_connection.view', 'own'),
  ('superadmin', 'm13.own_byok_connection.update', 'all'),
  ('developer_partner', 'm13.own_byok_connection.update', 'own'),
  ('superadmin', 'm13.own_byok_connection.rotate', 'all'),
  ('developer_partner', 'm13.own_byok_connection.rotate', 'own'),
  ('superadmin', 'm13.own_byok_connection.test', 'all'),
  ('developer_partner', 'm13.own_byok_connection.test', 'own'),
  ('superadmin', 'm13.own_byok_connection.enable', 'all'),
  ('developer_partner', 'm13.own_byok_connection.enable', 'own'),
  ('superadmin', 'm13.own_byok_connection.disable', 'all'),
  ('developer_partner', 'm13.own_byok_connection.disable', 'own'),
  ('superadmin', 'm13.own_byok_connection.disconnect', 'all'),
  ('developer_partner', 'm13.own_byok_connection.disconnect', 'own'),
  ('superadmin', 'm13.administrative_force_revoke_disable.execute', 'all'),
  ('superadmin', 'm14.commercial_administration.configure', 'all'),
  ('admin', 'm14.commercial_administration.configure', 'all'),
  ('superadmin', 'm14.commercial_administration.manage_commercial_resources', 'all'),
  ('admin', 'm14.commercial_administration.manage_commercial_resources', 'all'),
  ('superadmin', 'm14.commercial_purchase_access.own_purchase', 'all'),
  ('admin', 'm14.commercial_purchase_access.own_purchase', 'own'),
  ('manager', 'm14.commercial_purchase_access.own_purchase', 'own'),
  ('agent', 'm14.commercial_purchase_access.own_purchase', 'own'),
  ('developer_partner', 'm14.commercial_purchase_access.own_purchase', 'own'),
  ('buyer', 'm14.commercial_purchase_access.own_purchase', 'own'),
  ('superadmin', 'm14.commercial_purchase_access.access', 'all'),
  ('admin', 'm14.commercial_purchase_access.access', 'own'),
  ('manager', 'm14.commercial_purchase_access.access', 'own'),
  ('agent', 'm14.commercial_purchase_access.access', 'own'),
  ('developer_partner', 'm14.commercial_purchase_access.access', 'own'),
  ('buyer', 'm14.commercial_purchase_access.access', 'own'),
  ('superadmin', 'm14.refresh_allowance_entitlement.configure', 'all'),
  ('agent', 'm14.refresh_allowance_entitlement.configure', 'own'),
  ('superadmin', 'm14.refresh_allowance_entitlement.consume', 'all'),
  ('agent', 'm14.refresh_allowance_entitlement.consume', 'own'),
  ('superadmin', 'm15.qualification.administer', 'all'),
  ('admin', 'm15.qualification.administer', 'all'),
  ('manager', 'm15.qualification.administer', 'all'),
  ('agent', 'm15.qualification.administer', 'own'),
  ('developer_partner', 'm15.qualification.administer', 'own'),
  ('instructor', 'm15.qualification.administer', 'own'),
  ('superadmin', 'm15.qualification.evaluate', 'all'),
  ('admin', 'm15.qualification.evaluate', 'all'),
  ('manager', 'm15.qualification.evaluate', 'all'),
  ('agent', 'm15.qualification.evaluate', 'own'),
  ('developer_partner', 'm15.qualification.evaluate', 'own'),
  ('instructor', 'm15.qualification.evaluate', 'own'),
  ('superadmin', 'm15.award.award', 'all'),
  ('admin', 'm15.award.award', 'all'),
  ('manager', 'm15.award.award', 'all'),
  ('agent', 'm15.award.award', 'own'),
  ('superadmin', 'm15.award.revoke', 'all'),
  ('admin', 'm15.award.revoke', 'all'),
  ('manager', 'm15.award.revoke', 'all'),
  ('agent', 'm15.award.revoke', 'own'),
  ('superadmin', 'm15.award.manage', 'all'),
  ('admin', 'm15.award.manage', 'all'),
  ('manager', 'm15.award.manage', 'all'),
  ('agent', 'm15.award.manage', 'own'),
  ('superadmin', 'm15.title_authority_scope_binding.configure', 'all'),
  ('admin', 'm15.title_authority_scope_binding.configure', 'all'),
  ('manager', 'm15.title_authority_scope_binding.configure', 'all')
) AS g(role_code, permission_code, scope)
JOIN roles r ON r.code = g.role_code
JOIN permissions p ON p.action_code = g.permission_code
ON CONFLICT (role_id, permission_id) DO NOTHING;
